### ISSUE TITLE
Invalid log entry format: IP or username missing

### ISSUE THREAD

**Issue by ysomad** [kutovoys/xray-torrent-blocker#10]
Привет! Запустил на сервере с remnawave нодой, получаю в логах tblocker ошибку `Invalid log entry format: IP or username missing`.

Outbound на xray настроен в TORRENT blackhole, логи из remnwave маунтятся в /var/log/remnawave, в настройках xray-torrent-blocker также поставил пусть до этих логов в поле `LogFile`.

remnawave-node docker compose:
```yml
services:
  remnanode:
    container_name: remnanode
    hostname: remnanode
    image: remnawave/node:latest
    env_file:
      - .env
    network_mode: host
    volumes:
      - /var/log/remnawave:/var/log/supervisor
```

xray config:
```json
{
  "log": {
    "loglevel": "error"
  },
  "inbounds": [
    {
      "tag": "VLESS TCP REALITY",
      "port": 443,
      "listen": "0.0.0.0",
      "protocol": "vless",
      "settings": {
        "clients": [],
        "decryption": "none"
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "dest": "ftp.debian.org:443",
          "show": false,
          "xver": 0,
          "shortIds": [
            ""
          ],
          "publicKey": "",
          "privateKey": "",
          "fingerprint": "chrome",
          "serverNames": [
            "ftp.debian.org"
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "DIRECT",
      "protocol": "freedom"
    },
    {
      "tag": "BLOCK",
      "protocol": "blackhole"
    },
    {
      "tag": "TORRENT",
      "protocol": "blackhole"
    }
  ],
  "routing": {
    "rules": [
      {
        "ip": [
          "geoip:private"
        ],
        "type": "field",
        "outboundTag": "BLOCK"
      },
      {
        "type": "field",
        "domain": [
          "geosite:private"
        ],
        "outboundTag": "BLOCK"
      },
      {
        "type": "field",
        "protocol": [
          "bittorrent"
        ],
        "outboundTag": "TORRENT"
      },
      {
        "type": "field",
        "domain": [
          "geosite:category-ads"
        ],
        "outboundTag": "BLOCK"
      }
    ]
  }
}
```

xray логи:
```
2025/02/26 12:20:35 from ***:56020 accepted tcp:80.7.168.225:41766 [VLESS TCP REALITY >> DIRECT] email: ysomad
2025/02/26 12:20:35 from ***:56019 accepted tcp:78.140.7.33:16881 [VLESS TCP REALITY >> DIRECT] email: ysomad
2025/02/26 12:20:36 from ***:56030 accepted tcp:95.52.19.70:51413 [VLESS TCP REALITY -> TORRENT] email: ysomad
```

tblocker логи:
```
$ /opt/tblocker/tblocker -c /opt/tblocker/config.yaml
2025/02/26 12:21:59 XRay torrent-blocker: v0.3.0
2025/02/26 12:21:59 Service started on de1
2025/02/26 12:21:59 Seeked /var/log/remnawave/xray.out.log - &{Offset:0 Whence:2}
2025/02/26 12:22:35 Invalid log entry format: IP or username missing
```

Remna panel version: 1.3.2
Remna node version: 1.0.0

**Comment by ysomad** [comment]
Воспроизвел проблему тут: https://go.dev/play/p/LdlNiqcNyKi - Username regex в конфиге по умолчанию не ловит username

**Comment by ysomad** [comment]
Здесь пример с регуляркой, которая работает - https://go.dev/play/p/5T5kUPhuFHV
Чуть позже сделаю PR с фиксом

**Comment by kutovoys** [comment]
Для Remnawave достаточно в конфиге указать такое:
```
UsernameRegex: "email: (\\S+)"
```
В разных панелях это по-разному. И в данном случае это специально вынесено в конфиг для тонкой настройки под панель. 
Дефолтное значение сделано под Marzban - и оно таким и останется.

**Comment by kastov** [comment]
Привет! Небольшой совет.

```
    volumes:
      - /var/log/remnawave:/var/log/supervisor
```

Не нужно так монтировать и вытаскивать логи.

Правильный способ, в конфиге ядра ставим:

```
  "log": {
    "access": "/var/lib/remna/access.log",
    "error": "/var/lib/remna/access.log",
    "loglevel": "warning"
  },
```

Так мы явно выделяем логи ядра от всех других.

Запускаем ноду примерно вот так:

```
services:
  remnanode:
    image: remnawave/node:latest
    restart: always
    network_mode: host
    container_name: remnanode
    env_file: 
      - .env
    volumes:
      - "/var/lib/remna:/var/lib/remna"
```

На хостовой машине теперь логи ядра будут правильно примонтированы.
